version: '3'
services:
  leafy-postgres:
    image: ${DOCKER_HUB_USERNAME}/leafy-postgres:${LEAFY_POSTGRES_TAG}
    ports:
      - "5432:5432"
    volumes:
      - mydata
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
    restart: always

  leafy-backend:
    build: 
      context: ./leafy-backend
      dockerfile: Dockerfile
    image: ${DOCKER_HUB_USERNAME}/leafy-backend:1.0.0-compose
    command: sh -c "/script.sh"
    environment:
      - DB_URL=leafy-postgres
    ports:
      - "8080:8080"
    depends_on:
      - leafy-postgres
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 512M
    restart: on-failure
      
  leafy-front:
    image: ${DOCKER_HUB_USERNAME}/leafy-frontend:${LEAFY_FRONTEND_TAG}
    environment:
      - BACKEND_HOST=leafy-backend
    env_file:
      - ".env"
    ports:
      - "80:80"
    depends_on:
      - leafy-backend
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 64M
    restart: on-failure

volumes:
  mydata:

networks:
  leafy-network:
